[tool.black]
line-length = 120

[tool.mypy]
mypy_path = "extra_stubs"

files = "app"

strict = true
pretty = true
show_error_codes = true

[tool.ruff]
line-length = 120

select = [
    "A",
    "ARG",
    "B",
    "C4",
    "E",
    "F",
    "FBT",
    "I",
    "N",
    "PGH",
    "RUF",
    "S",
    "SIM",
    "T10",
    "T20",
    "UP",
    "W",
    "YTT",
]
ignore = ["ARG002", "E501"]
per-file-ignores = { "tests/**/*" = ["S101"] }

exclude = [
    "extra_stubs",
]

target-version = "py311"
