apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: bridgecrew
  labels:
    app: validate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validate
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - name: webhook
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: bridgecrew/whorf@sha256:43ef97edd2ea1d2b248e9db02061f0f934b82c87a5e329e7d6a18784fb8197e9
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command:
              - /bin/sh
              - -c
              - "pidof -x gunicorn"
        livenessProbe:
          initialDelaySeconds: 30
          exec:
            command:
              - /bin/sh
              - -c
              - "pidof -x gunicorn"
        ports:
        - containerPort: 8443
        env:
        - name: BC_SOURCE
          value: admissionController
        - name: CKV_GITHUB_CONFIG_FETCH_DATA
          value: "False"
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: whorfconfig # The ConfigMap this value comes from.
              key: debug        # Are we in debug mode?
        volumeMounts:
        - name: bridgecrew-secret
          readOnly: true
          mountPath: "/home/app/.bridgecrew"
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        - name: "config"
          mountPath: "/app/config"
        - name: "apptmp"
          mountPath: "/app/tmp"
        - name: "tmp"
          mountPath: "/tmp"
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 11000
        runAsGroup: 11000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: bridgecrew-secret
        secret:
          secretName: bridgecrew-secret
      - name: certs-volume
        secret:
          secretName: admission-tls
      - name: "config"
        projected:
          sources:
          - configMap:
              name: "checkovconfig"
          - configMap:
              name: "whorfconfig"
              items:
              - key: "whorf.yaml"
                path: "whorf.yaml"
      - emptyDir: {}
        name: apptmp
      - emptyDir: {}
        name: tmp
