name: PR

on:
  pull_request:

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DH_IMAGE_NAME: bridgecrew/checkov
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3.1.0
      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5  # v3.2.0
        with:
          context: .
          no-cache: true
          tags: ${{ env.DH_IMAGE_NAME }}:latest
