name: PR

on:
  pull_request:

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DH_IMAGE_NAME: bridgecrew/whorf
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0
      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5  # v3.2.0
        with:
          context: .
          no-cache: true
          tags: ${{ env.DH_IMAGE_NAME }}:latest
