name: PR

on:
  pull_request:

permissions: read-all

env:
  MIN_PYTHON_VERSION: "3.7"

jobs:
  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3
      - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v4
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python ${{ env.MIN_PYTHON_VERSION }}
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run python -m pytest tests
  docker-build:
    runs-on: ubuntu-latest
    env:
      DH_IMAGE_NAME: bridgecrew/whorf
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0
      - name: Build Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5  # v3.2.0
        with:
          context: .
          no-cache: true
          tags: ${{ env.DH_IMAGE_NAME }}:latest
