name: PR

on:
  pull_request:

permissions: read-all

env:
  MIN_PYTHON_VERSION: "3.11"

jobs:
  lint:
    uses: bridgecrewio/gha-reusable-workflows/.github/workflows/pre-commit.yaml@main
    with:
      python-version: "3.11"  # can't leverage env vars here
  mypy:
    uses: bridgecrewio/gha-reusable-workflows/.github/workflows/mypy.yaml@main
    with:
      python-version: "3.11"  # can't leverage env vars here

  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v3
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4
        with:
          python-version: ${{ env.MIN_PYTHON_VERSION }}
          cache: "pipenv"
          cache-dependency-path: "Pipfile.lock"
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python ${{ env.MIN_PYTHON_VERSION }}
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run python -m pytest tests

  docker-build:
    runs-on: ubuntu-latest
    env:
      DH_IMAGE_NAME: bridgecrew/whorf
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Build Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09  # v5.0.0
        with:
          context: .
          no-cache: true
          tags: ${{ env.DH_IMAGE_NAME }}:latest
